(() => {
  const csrf = document.querySelector('[name="csrf-token"]').content;
  const statusLabels = { queued: '排隊中', running: '執行中', pausing: '暫停中', paused: '已暫停', cancelling: '取消中', complete: '已完成', error: '失敗', cancelled: '已取消' };
  const recoveryDiagnostics = new Set(['browser_client_disconnected', 'browser_client_offline', 'browser_command_timeout', 'browser_navigation_timeout', 'bridge_transport_failed', 'secure_transport_failed']);
  const browserBase = window.location.pathname.startsWith('/web-content-fetch') ? '/web-content-fetch' : '';
  const node = (tag, props = {}, children = []) => { const value = document.createElement(tag); Object.entries(props).forEach(([key, item]) => { if (key === 'className') value.className = item; else if (key === 'textContent') value.textContent = item; else if (key.startsWith('data-')) value.setAttribute(key, item); else value[key] = item; }); children.forEach(child => value.append(child)); return value; };
  const prefixed = value => { const text = String(value || ''); return text.startsWith('/') && browserBase && !text.startsWith(browserBase + '/') ? browserBase + text : text; };
  const safeHttpUrl = value => { try { const parsed = new URL(String(value || '')); return ['http:', 'https:'].includes(parsed.protocol) ? parsed.href : ''; } catch { return ''; } };
  const makeUuid = () => { if (crypto.randomUUID) return crypto.randomUUID(); const bytes = new Uint8Array(16); crypto.getRandomValues(bytes); bytes[6] = (bytes[6] & 15) | 64; bytes[8] = (bytes[8] & 63) | 128; const hex = [...bytes].map(value => value.toString(16).padStart(2, '0')).join(''); return `${hex.slice(0, 8)}-${hex.slice(8, 12)}-${hex.slice(12, 16)}-${hex.slice(16, 20)}-${hex.slice(20)}`; };
  const browserServiceId = (() => { const key = 'web-content-fetch.serviceClientId'; let value = localStorage.getItem(key); if (!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value || '')) { value = makeUuid(); localStorage.setItem(key, value); } return value; })();
  document.querySelector('#browserServiceId').textContent = `本瀏覽器 service UUID：${browserServiceId}`;
  const setFeedback = (id, message, error = false) => { const element = document.querySelector(id); element.textContent = message || ''; element.className = `feedback${error ? ' error-text' : ''}`; };
  const statusLabel = status => statusLabels[status] || status || '未知';
  const progressInfo = job => { const p = job.progress || {}; if (Number.isInteger(p.image) && Number.isInteger(p.imageTotal)) return { label: `第 ${p.chapter || '?'} / ${p.chapterTotal || '?'} 章 · 圖片 ${p.image} / ${p.imageTotal}`, ratio: p.imageTotal ? p.image / p.imageTotal : 0 }; if (Number.isInteger(p.chapter) && Number.isInteger(p.chapterTotal)) return { label: `第 ${p.chapter} / ${p.chapterTotal} 章 · ${p.phase || ''}`, ratio: p.chapterTotal ? p.chapter / p.chapterTotal : 0 }; if (Number.isInteger(p.completed) && Number.isInteger(p.total) && p.total > 0) return { label: `${p.completed} / ${p.total}`, ratio: p.completed / p.total }; return { label: p.phase || '等待中', ratio: 0 }; };
  const appendDownload = (parent, download) => { if (!download?.href) return; const link = node('a', { className: 'download-link', href: prefixed(download.href), download: download.filename || '', textContent: `${download.format || '檔案'} · ${download.filename || '下載'}` }); parent.append(link); };
  const appendActions = (parent, job) => { const actions = []; const add = (action, label, className = 'button ghost') => actions.push(node('button', { className, type: 'button', textContent: label, 'data-job-id': job.id, 'data-action': action })); if (['queued', 'running'].includes(job.status)) add('pause', '暫停'); if (job.status === 'paused') add('resume', '恢復'); if (['queued', 'running', 'pausing', 'paused', 'cancelling'].includes(job.status)) add('cancel', '取消並刪除', 'button danger'); if (['complete', 'error', 'cancelled'].includes(job.status)) add('delete', '清除紀錄與檔案', 'button danger'); if (job.status === 'error' && recoveryDiagnostics.has(job.diagnostic)) add('resume', '保留進度並恢復', 'button secondary'); actions.forEach(action => parent.append(action)); };
  const renderJob = job => { const progress = progressInfo(job); const badge = node('span', { className: `badge ${job.status || ''}`, textContent: statusLabel(job.status) }); const title = node('h3', { className: 'job-title', textContent: job.title || job.url || '未命名工作' }); const top = node('div', { className: 'job-top' }, [node('div', {}, [title, node('a', { className: 'job-url', href: safeHttpUrl(job.url) || '#', target: '_blank', rel: 'noopener noreferrer', textContent: job.url || '無網址' })]), badge]); const bar = node('div', { className: 'progress-bar' }); bar.style.width = `${Math.max(0, Math.min(100, progress.ratio * 100))}%`; const summary = node('p', { className: 'job-meta' }, [node('span', { textContent: `進度：${progress.label}` }), node('span', { textContent: `類型：${job.kind || '-'}` }), node('span', { textContent: `章節：${job.chapterCount || job.progress?.chapterTotal || '-'}` })]); const left = node('div', {}, [summary, node('div', { className: 'progress-track' }, [bar])]); if (job.diagnostic) left.append(node('p', { className: 'error-text', textContent: `診斷：${job.diagnostic}` })); const outputPanel = node('div', { className: 'outputs' }, [node('h3', { textContent: '可下載檔案' })]); if (job.downloadAll) { const all = node('a', { className: 'all-download', href: prefixed(job.downloadAll), textContent: '下載全部已完成檔案' }); outputPanel.append(all); } const groups = Array.isArray(job.outputGroups) ? job.outputGroups : []; if (groups.length) groups.forEach(group => { const links = node('div', { className: 'download-list' }); (group.downloads || []).forEach(download => appendDownload(links, download)); outputPanel.append(node('div', { className: 'output-group' }, [node('strong', { textContent: group.label || `第 ${(group.chapterIndex || 0) + 1} 章` }), links])); }); else if (Array.isArray(job.downloads) && job.downloads.length) { const links = node('div', { className: 'download-list' }); job.downloads.forEach(download => appendDownload(links, download)); outputPanel.append(links); } else outputPanel.append(node('p', { className: 'empty', textContent: job.status === 'running' ? '完成的章節會在這裡出現。' : '尚未產生可下載檔案。' })); const actions = node('div', { className: 'job-actions' }); appendActions(actions, job); return node('article', { className: 'job-card' }, [top, node('div', { className: 'job-grid' }, [node('div', {}, [left, actions]), outputPanel])]); };
  const renderJobs = jobs => { const list = document.querySelector('#jobs'); list.textContent = ''; const counts = jobs.reduce((result, job) => { result[job.status] = (result[job.status] || 0) + 1; return result; }, {}); document.querySelector('#stats').replaceChildren(...[['running', '執行中'], ['queued', '排隊'], ['complete', '完成'], ['error', '失敗']].map(([key, label]) => node('span', { className: 'stat' }, [node('strong', { textContent: counts[key] || 0 }), node('span', { textContent: label })]))); if (!jobs.length) { list.append(node('div', { className: 'job-card empty', textContent: '目前沒有下載工作。' })); return; } jobs.slice().reverse().forEach(job => list.append(renderJob(job))); };
  const fillSelect = (id, profiles, selected) => { const select = document.querySelector(id); select.textContent = ''; profiles.forEach(profile => select.append(node('option', { value: profile.bindingId, textContent: `${profile.serviceClientId} · browser ${profile.browserClientId} · ${profile.bridgeUrl}` }))); if (!profiles.length) select.append(node('option', { value: '', textContent: '尚未綁定' })); select.value = selected || ''; };
  const renderBinding = binding => { const profiles = binding.bindings || []; fillSelect('#bindingSelect', profiles, binding.activeBindingId); fillSelect('#jobBinding', profiles, binding.activeBindingId); document.querySelector('#binding').textContent = `${binding.paired ? '已綁定' : '尚未綁定'} · ${binding.bridgeUrl || '-'} · callback ${binding.callbackUrl || '-'}`; const connection = document.querySelector('#connection'); connection.dataset.state = binding.paired ? 'ok' : 'bad'; connection.textContent = binding.paired ? 'Bridge 已連線' : 'Bridge 未連線'; };
  const render = data => { renderBinding(data.binding || {}); renderJobs(data.jobs || []); };
  async function refresh() { try { const response = await fetch(`${browserBase}/api/state`); if (!response.ok) throw new Error(`state_http_${response.status}`); const data = await response.json(); document.querySelector('#bridgeUrl').value = data.binding?.bridgeUrl || ''; document.querySelector('#callbackUrl').value = data.binding?.callbackUrl || ''; render(data); } catch (error) { const connection = document.querySelector('#connection'); connection.dataset.state = 'bad'; connection.textContent = '服務未連線'; setFeedback('#status', error.message, true); } }
  async function post(path, body = {}) { return fetch(`${browserBase}${path}`, { method: 'POST', headers: { 'content-type': 'application/json', 'x-csrf-token': csrf }, body: JSON.stringify(body) }); }
  document.querySelector('#saveConfig').onclick = async () => { const response = await post('/api/config', { bridgeUrl: document.querySelector('#bridgeUrl').value, callbackUrl: document.querySelector('#callbackUrl').value, activeBindingId: document.querySelector('#bindingSelect').value }); setFeedback('#configStatus', response.ok ? '設定已儲存' : '設定失敗', !response.ok); await refresh(); };
  document.querySelector('#pair').onclick = async () => { const response = await post('/api/bridge/pair', { code: document.querySelector('#pairCode').value, bridgeUrl: document.querySelector('#bridgeUrl').value, serviceClientId: browserServiceId }); setFeedback('#configStatus', response.ok ? 'Bridge 綁定成功' : 'Bridge 綁定失敗', !response.ok); await refresh(); };
  document.querySelector('#form').addEventListener('submit', async event => { event.preventDefault(); const response = await post('/api/jobs', { url: document.querySelector('#url').value, kind: document.querySelector('#kind').value, bindingId: document.querySelector('#jobBinding').value }); setFeedback('#status', response.ok ? '已加入佇列' : '加入失敗', !response.ok); await refresh(); });
  document.querySelector('#clearTerminal').onclick = async () => { if (!confirm('清除所有已結束工作紀錄，並刪除相關 EPUB、KEPUB 與暫存檔？')) return; const response = await post('/api/jobs/clear-terminal'); setFeedback('#status', response.ok ? '已清除已結束工作與相關檔案' : '清除失敗', !response.ok); await refresh(); };
  document.querySelector('#jobs').addEventListener('click', async event => { const button = event.target.closest('[data-action]'); if (!button) return; const action = button.dataset.action; const id = button.dataset.jobId; if (action === 'cancel' && !confirm('取消後會刪除這個工作已下載的檔案，確定繼續嗎？')) return; if (action === 'delete' && !confirm('刪除這個工作紀錄與相關檔案，確定繼續嗎？')) return; const response = await post(`/api/jobs/${encodeURIComponent(id)}/${action}`); if (!response.ok) setFeedback('#status', '操作失敗', true); await refresh(); });
  const events = new EventSource(`${browserBase}/api/events`); events.onmessage = event => { try { render(JSON.parse(event.data)); } catch { setFeedback('#status', '進度資料格式錯誤', true); } }; events.onerror = () => { const connection = document.querySelector('#connection'); if (connection.dataset.state !== 'ok') { connection.dataset.state = 'bad'; connection.textContent = '進度串流重新連線中'; } };
  refresh();
})();
